### ISSUE TITLE
GrowthPush.registerClient causes NullPointerException.

### ISSUE THREAD

**Issue by satorufujiwara** [SIROK/growthbeat-android#45]
[GrowthPush.requestRegistrationId(String,Environment)](https://github.com/growthbeat/growthbeat-android/blob/1.2.5/growthbeat/src/main/java/com/growthpush/GrowthPush.java#L96)を呼ぶ前に、[GrowthPush.registerClient(String)](https://github.com/growthbeat/growthbeat-android/blob/1.2.5/growthbeat/src/main/java/com/growthpush/GrowthPush.java#L121)を呼ぶと[Clientクラスの69行目](https://github.com/growthbeat/growthbeat-android/blob/1.2.5/growthbeat/src/main/java/com/growthpush/model/Client.java#L69)でNullPointerExceptionが発生します。

GrowtPushのenvironmentフィールドがrequestRegsitrationId内で初期化されているため起きると思われます。

また、requestRegistrationIdは[内部で使っているGoogleCloudMessaging.register(String)](https://github.com/growthbeat/growthbeat-android/blob/1.2.5/growthbeat/src/main/java/com/growthpush/GrowthPush.java#L113)が[Deprecatedになっている](https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging.html#register%28java.lang.String...%29)ため使わないようにしています。

GCMの最新の仕様は以下にあります。
https://developers.google.com/cloud-messaging/android/client

**Comment by sangotaro** [comment]
ご報告ありがとございます。
v1.2.6にて`GrowthPush.registerClient()`でenvironmentを指定できるようにしました。
