### ISSUE TITLE
Uncaught Exception: com.growthbeat.GrowthbeatException; Failed create HttpURLConnection

### ISSUE THREAD

**Issue by magiepooh** [SIROK/growthbeat-android#47]
`BaseHttpClient#generateHttpURLConnection`で`GrowthbeatException`が投げられた時に、exceptionがキャッチされていないので`GrowthPush#trackEvent`の`Event.create`内部のpostでこのexceptionが発生した時に落ちます。
`GrowthPush#trackEvent`内で`GrowthPushException`はcatchされていますが、`GrowthBeatException`も考慮しないといけないのではないのでしょうか？
また、詳しく見ていませんが、setTagでも同じ現象で落ちる可能性がある気がします。

**Comment by sangotaro** [comment]
ご報告ありがとございます。
仰るとおり、`GrowthBeatException` も考慮しなくてはいけません。大変失礼いたしました。

アプリが落ちるとのことですが、`Uncaught Exception: com.growthbeat.GrowthbeatException;`のようなログは出ていますでしょうか？
スレッド内のExceptionは、下記にて最終的にUncaught Exceptionとして処理することを想定しています。
https://github.com/growthbeat/growthbeat-android/blob/master/growthbeat/src/main/java/com/growthbeat/GrowthbeatThreadExecutor.java#L42

お手数お掛けしすが、ご確認お願い致します。

**Comment by magiepooh** [comment]
@sangotaro 
`Uncaught Exception: com.growthbeat.GrowthbeatException;`のログが出ていました。ということは実際は落ちないということですかね。
もしかしたら、落ちたのは違う原因だったかもしれません、すみません。

**Comment by sangotaro** [comment]
ご確認ありがとございます。
SDK側に原因がありそうであれば、ご連絡頂けると助かります。

`GrowthBeatException` をcatchしていないのは、こちらの意図ではないので、
適切なエラーメッセージが出るように、今後のアップデートで修正します。
