### ISSUE TITLE
why do not supported large icon?

### ISSUE THREAD

**Issue by jwyjoy** [SIROK/growthbeat-android#49]
hello, guys!

we can setting large icon. 
but, this library not supported yet.

[following this guidelines](http://developer.android.com/intl/ja/design/patterns/notifications.html#guidelines)

I think the this library.
Only by adding some of the source and the metadata
It will be realized that.

[add String this](https://github.com/growthbeat/growthbeat-android/blob/639f19d29f61a25a6d80df232cd6af88cf6b1557/growthbeat/src/main/java/com/growthpush/GrowthPush.java#L31-L34)

[add some source](https://github.com/growthbeat/growthbeat-android/blob/639f19d29f61a25a6d80df232cd6af88cf6b1557/growthbeat/src/main/java/com/growthpush/handler/BaseReceiveHandler.java#L97-L109)

and update your guidelines.

**Comment by mattak** [comment]
:+1:

**Comment by pine** [comment]
:+1:

**Comment by jwyjoy** [comment]
not response
