### ISSUE TITLE
Is it possible to use an android:maxSdkVersion function on uses-permission?

### ISSUE THREAD

**Issue by yhirano** [SIROK/growthbeat-android#51]
Your [document](http://support.growthbeat.com/sdk/android/guide/) is written adding a GET_ACCOUNTS permission to manifest as described below.

``` xml
<!-- under API 15 -->
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
```

However, this permission look like that isn't used in more than SDK version 16.
Therefore, Is it possible to use an android:maxSdkVersion function on uses-permission as descripted below?

``` xml
<uses-permission android:name="android.permission.GET_ACCOUNTS" android:maxSdkVersion="14" />
```

**Comment by ohageeq** [comment]
Not need GET_ACCOUNTS permission.
Fixed document.
