### ISSUE TITLE
Bintrayに最新バージョンがアップロードされていない

### ISSUE THREAD

**Issue by futabooo** [SIROK/growthbeat-android#79]
1.2.7までしかアップロードされていないようです。

![2016-07-22 22 32 32](https://cloud.githubusercontent.com/assets/944185/17058603/406c1fcc-505c-11e6-98cd-020473987241.png)

**Comment by konomae** [comment]
一時的に jitpack でしのいでましたが2.0.2 がアップされたようですね

https://bintray.com/growthbeat/maven/growthbeat-android/2.0.2
https://jitpack.io/#growthbeat/growthbeat-android/2.0.2

**Comment by futabooo** [comment]
@konomae 
おお！
ありがとうございます！
