### ISSUE TITLE
Remove tag 'application' in AndroidManifest.xml

### ISSUE THREAD

**Issue by mtsrst** [SIROK/growthbeat-android#85]
2.0.4のAndroidManifest.xmlに'application'タグが入ってしまっているので削除して欲しい。
ライブラリなので不要なはず。
アプリ側の<application>ダグと重複してしまうので問題起きます。

**Comment by ohageeq** [comment]
こちらのコミットで対応しました。次回リリースに含まれる予定です。
https://github.com/growthbeat/growthbeat-android/commit/ff711574086f9f99a48c2bc6df9d4151a39d475e

**Comment by ohageeq** [comment]
SDKを本リリースしました。
https://github.com/growthbeat/growthbeat-android/releases/tag/2.0.5
